export const books = [
  {
    id: 'c1eefd6b-d0fa-40fe-8594-1487e4be3731',
    title: 'Effective Python',
    author: 'William Gibson',
    release_date: '2017',
    number_of_purchases: 23,
    likes: 19,
    rating: 3.0,
    price: 23.10,
    currency: 'USD',
    available_copies: 12,
    full_description: 'A book for the bookish',
    image_url: 'https://res.cloudinary.com/zokky/image/upload/v1645398393/effective_python.png',
    tags: ['Beauty', 'Education'],
    genres: ['Motivation']
  },
  {
    id: '06130e95-d336-448e-ae71-ffe533aafdfc',
    title: 'Effective Python',
    author: 'William Gibson',
    release_date: '2017',
    number_of_purchases: 23,
    likes: 19,
    rating: 3.0,
    price: 23.10,
    currency: 'NGN',
    available_copies: 10,
    full_description: 'A book for the bookish',
    image_url: 'https://res.cloudinary.com/zokky/image/upload/v1645405075/effective_engineer.png',
    tags: [],
    genres: []
  },
  {
    id: 'ec15e763-6858-4c72-9a8b-ade83ccae3e2',
    title: 'Effective Python',
    author: 'William Gibson',
    release_date: '2017',
    number_of_purchases: 23,
    likes: 19,
    rating: 3.0,
    price: 23.10,
    currency: 'NGN',
    available_copies: 0,
    full_description: 'A book for the bookish',
    image_url: 'https://res.cloudinary.com/zokky/image/upload/v1645405076/big_magic.png',
    tags: [],
    genres: []
  },
  // {
  //   id: '486c5da8-a39b-4662-9a4e-6f235b291065',
  //   title: 'Effective Python',
  //   author: 'William Gibson',
  //   release_date: '2017',
  //   number_of_purchases: 23,
  //   likes: 19,
  //   rating: 3.0,
  //   price: 23.10,
  //   currency: 'USD',
  //   available_copies: 12,
  //   full_description: 'A book for the bookish',
  //   image_url: 'https://res.cloudinary.com/zokky/image/upload/v1645398393/effective_python.png',
  //   tags: [],
  //   genres: []
  // },
  // {
  //   id: 'fd01cdbf-bf6b-47cc-a309-777b5d12228e',
  //   title: 'Effective Python',
  //   author: 'William Gibson',
  //   release_date: '2017',
  //   number_of_purchases: 23,
  //   likes: 19,
  //   rating: 3.0,
  //   price: 23.10,
  //   currency: 'USD',
  //   available_copies: 12,
  //   full_description: 'A book for the bookish',
  //   image_url: 'https://res.cloudinary.com/zokky/image/upload/v1645405075/effective_engineer.png',
  //   tags: [],
  //   genres: []
  // },
  // {
  //   id: 'dda4374d-e4eb-45b8-910c-7b708190140b',
  //   title: 'Effective Python',
  //   author: 'William Gibson',
  //   release_date: '2017',
  //   number_of_purchases: 0,
  //   likes: 19,
  //   rating: 3.0,
  //   price: 23.10,
  //   currency: 'USD',
  //   available_copies: 12,
  //   full_description: 'A book for the bookish',
  //   image_url: 'https://res.cloudinary.com/zokky/image/upload/v1645405076/big_magic.png',
  //   tags: [],
  //   genres: []
  // },
  // {
  //   id: '30fdf7ca-4579-402c-80a0-3efb88d4623f',
  //   title: 'Effective Python',
  //   author: 'William Gibson',
  //   release_date: '2017',
  //   number_of_purchases: 23,
  //   likes: 19,
  //   rating: 3.0,
  //   price: 23.10,
  //   currency: 'NGN',
  //   available_copies: 0,
  //   full_description: 'A book for the bookish',
  //   image_url: 'https://res.cloudinary.com/zokky/image/upload/v1645398393/effective_python.png',
  //   tags: [],
  //   genres: []
  // },
  // {
  //   id: '52578046-5e1b-40b7-88ae-71f8c9fde59e',
  //   title: 'Effective Python',
  //   author: 'William Gibson',
  //   release_date: '2017',
  //   number_of_purchases: 23,
  //   likes: 19,
  //   rating: 3.0,
  //   price: 23.10,
  //   currency: 'NGN',
  //   available_copies: 12,
  //   full_description: 'A book for the bookish',
  //   image_url: 'https://res.cloudinary.com/zokky/image/upload/v1645405075/effective_engineer.png',
  //   tags: [],
  //   genres: []
  // }
]